require('dotenv').config();

const {
  PORT,
  MONGODB_URI,
  NODE_ENV,
  CLOUDFRONT_DIST_DOMAIN,
  ADMIN_USERNAME,
  ADMIN_PASSWORD,
  JWT_SECRET,
  S3_BUCKET_NAME,
  S3_BUCKET_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
} = process.env;

export default {
  PORT,
  MONGODB_URI,
  NODE_ENV,
  CLOUDFRONT_DIST_DOMAIN,
  ADMIN_USERNAME,
  ADMIN_PASSWORD,
  JWT_SECRET,
  S3_BUCKET_NAME,
  S3_BUCKET_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
};
